#配置一个binding（对应rabbitmq中的Exchange)
spring:
  cloud:
    stream:
      bindings:
        inputMy:
          destination: myBinding
          group: persistence #存放消息的队列持久化
        outputMy:
          destination: myBinding
        fallbackInput:
          detination: fallbackOutput
        fallbackOutput:
          destination: fallbackInput